<div>
    @slot('header')
        TABLA DE FUNCIONARIOS
    @endslot
    <!-- CREAR FUNCIONES PARA ORDENAR POR DATOS, AGREGAR BARRA DE BUSQUEDA Y CREAR NUEVAS SECCIONES PARA
    VER LOS CAMPOS Y ESTADISTICAS AL RESPECTO, ADEMAS DE QUE CLIQUEANDO UN REGISTRO SE VEA TODA LA INFORMACION
    DEL FUNCIONARIO, PERO TAMBIEN QUE AL CLIQUEAR UN CAMPO IMPORTANTE (COMO ARMA, ESTADO, PROMO, GENERO, EDAD,
    DEPENDENCIA) SE ABRA UN GRAFICO RELACIONADO -->
    <!--TABLA DE funcionarios-->
    @include('components.table')
</div>
